### ISSUE TITLE
Support supervision for chat messages

### ISSUE THREAD

**Issue by joehewett** [asteroidai/asteroid-python-sdk#9]
Regular chat messages can also need supervising, not just the tool calls inside those chat messages.

To support this, I suggest that we reuse the tool paradigm that we already support. We can consider the case where the LLM returns text as calling a 'tool'. 

Then, when we observe an LLM message return from the client, we should check:
a) does the message have text but 0 tool calls?
b) && is there a chat_tool registered?

If so, we should submit supervision requests/results for the registered chain just as we do normally.

**Comment by mlcocdav** [comment]
Regarding `chat message + tool calls` -  I think here the tool calls take precedence so I would treat it the same as `tool calls only`. I wouldn't try to support some esoteric case of supervising chat messages and tool calls at the same time.

**Comment by joehewett** [comment]
> Regarding `chat message + tool calls` - I think here the tool calls take precedence so I would treat it the same as `tool calls only`. I wouldn't try to support some esoteric case of supervising chat messages and tool calls at the same time.

Support could probably be added down the line if needed anyway although I haven't thought too hard about it

**Comment by mlcocdav** [comment]
@joehewett 

So I believe on the client side:
1. I will add chat supervisor role: ✅ 
```
class SupervisorType(str, Enum):
    CLIENT_SUPERVISOR = "client_supervisor"
    HUMAN_SUPERVISOR = "human_supervisor"
    NO_SUPERVISOR = "no_supervisor"
    CHAT_SUPERVISOR = "chat_supervisor"
```
2. Use CHAT_SUPERVISOR role when registering new supervisors  ✅ 
3. I will not assign these supervisors to any tool? Or will I have some `tool_id` that corresponds to `chat_tool`? ❓
4. The next question is how to register chain of supervisors - that one is tied to a `tool_id`, so @joehewett what should I send there instead? This depends on the point 3.
<img width="1198" alt="Image" src="https://github.com/user-attachments/assets/4cb3e07f-4dc8-40fe-b596-83d9553fc705" />❓
- also 
4. To run chat supervisors in the supervisor chains the same as with tool supervisors, i need to create `tool_call_id` - What should I create here
<img width="1400" alt="Image" src="https://github.com/user-attachments/assets/84244afc-1589-44fe-81b9-d95e138700be" /> ❓

5. Then I can run submit requests/results normally on the supervisor chains  ✅

**Comment by joehewett** [comment]
I suggest that we register a tool call the chat_tool. If you think about the LLM as just outputting a message as being a tool call, then this makes some sense conceptually. So regsiter a chat_tool, and if you notice that the LLM message has no tool calls then we can consider it to be a call of the chat_tool.

**Comment by mlcocdav** [comment]
Ok makes sense, I will try to implement it this way on the client side. You just need to support the `CHAT_SUPERVISOR` type and I can start testing it.
